# Generated by Django 4.0 on 2021-12-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderBookRecord',
            new_name='BTCTRY',
        ),
    ]
