# Generated by Django 4.0 on 2021-12-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_orderbookrecord_btctry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCTRYStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('total_volume', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='btctry',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
